services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.book.author:
        class: App\Admin\Book\AuthorAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_book_author' ] ]
            - [ setBaseRoutePattern,    [ 'book-author' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Book\Author'
                controller: App\Controller\Admin\CRUD\AdminCRUDController
                manager_type: orm
                group: MENU_GROUP.BOOK
                label: MENU.BOOK_AUTHOR

    admin.book.category:
        class: App\Admin\Book\CategoryAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_book_category' ] ]
            - [ setBaseRoutePattern,    [ 'book-category' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Book\Category'
                controller: App\Controller\Admin\CRUD\AdminCRUDController
                manager_type: orm
                group: MENU_GROUP.BOOK
                label: MENU.BOOK_CATEGORY

    admin.book:
        class: App\Admin\Book\BookAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_book' ] ]
            - [ setBaseRoutePattern,    [ 'book' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Book\Book'
                controller: App\Controller\Admin\CRUD\Book\BookCRUDController
                manager_type: orm
                group: MENU_GROUP.BOOK
                label: MENU.BOOK

    admin.order:
        class: App\Admin\OrderAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_order' ] ]
            - [ setBaseRoutePattern,    [ 'order' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Order'
                controller: App\Controller\Admin\CRUD\OrderCRUDController
                manager_type: orm
                group: MENU_GROUP.BOOK
                label: MENU.ORDER

    admin.reading:
        class: App\Admin\ReadingAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_reading' ] ]
            - [ setBaseRoutePattern,    [ 'reading' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Reading'
                controller: App\Controller\Admin\CRUD\AdminCRUDController
                manager_type: orm
                group: MENU_GROUP.BOOK
                label: MENU.READING
