services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.mail_template.forgot_password:
        class: App\Admin\MailTemplate\EditForgotPasswordMailTemplateAdmin
        calls:
            - [ setBaseRouteName,       ['admin_forgot_password_mail_template'] ]
            - [ setBaseRoutePattern,    ['forgot-password-mail-template'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\MailTemplate\ForgotPasswordMailTemplate,  manager_type: orm, group: MENU_GROUP.MAIL_TEMPLATE, label: MENU.MAIL_TEMPLATE.FORGOT_PASSWORD }

    admin.mail_template.register:
        class: App\Admin\MailTemplate\EditRegisterMailTemplateAdmin
        calls:
            - [ setBaseRouteName,       ['admin_register_mail_template'] ]
            - [ setBaseRoutePattern,    ['register-mail-template'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\MailTemplate\RegisterMailTemplate, manager_type: orm, group: MENU_GROUP.MAIL_TEMPLATE, label: MENU.MAIL_TEMPLATE.REGISTER }

    admin.mail_template.register_notification:
        class: App\Admin\MailTemplate\EditRegisterNotificationMailTemplateAdmin
        calls:
            - [ setBaseRouteName,       ['admin_register_notification_mail_template'] ]
            - [ setBaseRoutePattern,    ['register-notification-mail-template'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\MailTemplate\RegisterNotificationMailTemplate, manager_type: orm, group: MENU_GROUP.MAIL_TEMPLATE, label: MENU.MAIL_TEMPLATE.REGISTER_NOTIFICATION }

    admin.mail_template.dealer_request:
        class: App\Admin\MailTemplate\EditDealerRequestMailTemplateAdmin
        calls:
            - [ setBaseRouteName,       ['admin_dealer_request_mail_template'] ]
            - [ setBaseRoutePattern,    ['dealer-request-mail-template'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\MailTemplate\DealerRequestMailTemplate, manager_type: orm, group: MENU_GROUP.MAIL_TEMPLATE, label: MENU.MAIL_TEMPLATE.DEALER_REQUEST }
