services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.menu.bottom:
        class: App\Admin\Menu\BottomMenuAdmin
        calls:
            - [ setBaseRouteName,       ['admin_menu_bottom'] ]
            - [ setBaseRoutePattern,    ['menu-bottom'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Menu\BottomMenu', manager_type: orm, group: MENU_GROUP.MENU, label: MENU.MENU.BOTTOM }

    admin.menu.footer:
        class: App\Admin\Menu\FooterMenuAdmin
        calls:
            - [ setBaseRouteName,       ['admin_menu_footer'] ]
            - [ setBaseRoutePattern,    ['menu-footer'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Menu\FooterMenu', manager_type: orm, group: MENU_GROUP.MENU, label: MENU.MENU.FOOTER }
