services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.filter_group:
        class: App\Admin\Filter\FilterGroupAdmin
        calls:
            - [ setBaseRouteName,       ['admin_filter_group'] ]
            - [ setBaseRoutePattern,    ['filter-group'] ]
            - [ addChild,               ['@admin.filter', 'filterGroup'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Filter\FilterGroup', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.FILTER_GROUP }

    admin.filter:
        class: App\Admin\Filter\FilterAdmin
        calls:
            - [ setBaseRouteName,       ['admin_filter'] ]
            - [ setBaseRoutePattern,    ['filter'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Filter\Filter', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.FILTER }

    admin.product:
        class: App\Admin\Product\ProductAdmin
        calls:
            - [ setBaseRouteName,       ['admin_product'] ]
            - [ setBaseRoutePattern,    ['product'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Product\Product', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.PRODUCT }

    admin.use_case:
        class: App\Admin\Product\ProductSetAdmin
        calls:
            - [ setBaseRouteName,       ['admin_use_case'] ]
            - [ setBaseRoutePattern,    ['use-case'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Product\ProductSet', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.USE_CASE }

    admin.use_case_product:
        class: App\Admin\Product\ProductSetProductAdmin
        calls:
            - [ setBaseRouteName,       ['admin_use_case_product'] ]
            - [ setBaseRoutePattern,    ['use-case-product'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Product\ProductSetProduct', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.USE_CASE_PRODUCT, show_in_dashboard: false }

    admin.decision:
        class: App\Admin\DecisionAdmin
        calls:
            - [ setBaseRouteName,       ['admin_decision'] ]
            - [ setBaseRoutePattern,    ['decision'] ]
            - [ addChild,               ['@admin.decision.children', 'parentDecision' ]]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Decision', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.DECISION }

    admin.decision.children:
        class: App\Admin\DecisionAdmin
        calls:
            - [ setBaseRouteName,       ['admin_decision_child'] ]
            - [ setBaseRoutePattern,    ['decision-child'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Decision', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.DECISION_CHILD, show_in_dashboard: false }

    admin.slider:
        class: App\Admin\Slider\SliderAdmin
        calls:
            - [ setBaseRouteName,       ['admin_slider'] ]
            - [ setBaseRoutePattern,    ['slider'] ]
            - [ addChild,               ['@admin.slide', 'slider' ]]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Slider\Slider', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.SLIDER }

    admin.slide:
        class: App\Admin\Slider\SlideAdmin
        calls:
            - [ setBaseRouteName,       ['admin_slide'] ]
            - [ setBaseRoutePattern,    ['slide'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Slider\Slide', manager_type: orm, group: MENU_GROUP.PRODUCT_CATALOG, label: MENU.SLIDE, show_in_dashboard: false }
