services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.reading:
        class: App\Admin\ReadingAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_reading' ] ]
            - [ setBaseRoutePattern,    [ 'reading' ] ]
            - [ setTemplate, [ 'list', 'admin/reading/list.html.twig' ] ]
            - [ setTemplate, [ 'edit', 'admin/reading/edit.html.twig' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Reading'
                controller: App\Controller\Admin\CRUD\ReadingCRUDController
                manager_type: orm
                group: MENU_GROUP.READING
                label: MENU.READING

    admin.reading.prolong:
        class: App\Admin\ReadingProlongAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_reading_prolong' ] ]
            - [ setBaseRoutePattern,    [ 'reading-prolong' ] ]
            - [ setTemplate, [ 'list', 'admin/reading/list.html.twig' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Reading'
                controller: App\Controller\Admin\CRUD\ReadingCRUDController
                manager_type: orm
                group: MENU_GROUP.READING
                label: MENU.READING_PROLONG

    admin.reading.expire:
        class: App\Admin\ReadingExpireAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_reading_expire' ] ]
            - [ setBaseRoutePattern,    [ 'reading-expire' ] ]
            - [ setTemplate, [ 'list', 'admin/reading/list.html.twig' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Reading'
                controller: App\Controller\Admin\CRUD\ReadingCRUDController
                manager_type: orm
                group: MENU_GROUP.READING
                label: MENU.READING_EXPIRE
