services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.settings.general:
        class: App\Admin\Settings\EditGeneralSettingsAdmin
        calls:
            - [ setBaseRouteName,       ['admin_general_settings' ] ]
            - [ setBaseRoutePattern,    ['general-settings' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\Settings\GeneralSettings'
                controller: App\Controller\Admin\CRUD\AdminCRUDController
                manager_type: orm
                group: MENU_GROUP.SETTINGS
                label: MENU.SETTINGS.GENERAL
