services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.system.mail_log:
        class: App\Admin\MailLogAdmin
        calls:
            - [ setBaseRouteName,       ['admin_mail_log'] ]
            - [ setBaseRoutePattern,    ['mail-log'] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\MailLog', manager_type: orm, group: MENU_GROUP.SYSTEM, label: MENU.SYSTEM.MAIL_LOG }

#    admin.system.cron_command:
#        class: App\Admin\CronCommandAdmin
#        arguments: [~, App\Entity\CronCommand, App\Controller\Admin\CRUD\CronCommandCRUDController]
#        calls:
#            - [ setBaseRouteName,       ['admin_cron_command'] ]
#            - [ setBaseRoutePattern,    ['cron-command'] ]
#            - [ setTemplate,            ['list', 'admin\CRUD\cron_command\list.html.twig'] ]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: MENU_GROUP.SYSTEM, label: MENU.SYSTEM.CRON_COMMAND }
