services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    admin.user:
        class: App\Admin\User\AllUserAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user' ] ]
            - [ setBaseRoutePattern,    [ 'user' ] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\User\User', manager_type: orm, group: MENU_GROUP.USER, label: MENU.USER_ALL }

    admin.user.admin:
        class: App\Admin\User\UserAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_admin' ] ]
            - [ setBaseRoutePattern,    [ 'user-admin' ] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\User\User', manager_type: orm, group: MENU_GROUP.USER, label: MENU.USER_ADMIN }

    admin.user.librarian:
        class: App\Admin\User\UserLibrarianAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_librarian' ] ]
            - [ setBaseRoutePattern,    [ 'user-librarian' ] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\User\User', manager_type: orm, group: MENU_GROUP.USER, label: MENU.USER_LIBRARIAN }

    admin.user.reader:
        class: App\Admin\User\UserReaderAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_reader' ] ]
            - [ setBaseRoutePattern,    [ 'user-reader' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\User\User'
                controller: App\Controller\Admin\CRUD\UserReaderCRUDController
                manager_type: orm
                group: MENU_GROUP.USER
                label: MENU.USER_READER

    admin.user.profile:
        class: App\Admin\User\Profile\EditUserProfileAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_profile' ] ]
            - [ setBaseRoutePattern,    [ 'user-profile' ] ]
        tags:
            -   name: sonata.admin
                model_class: 'App\Entity\User\User'
                manager_type: orm
                group: MENU_GROUP.USER
                label: MENU.USER_PROFILE.EDIT

    admin.user.profile.order:
        class: App\Admin\User\Profile\OrderUserProfileAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_order' ] ]
            - [ setBaseRoutePattern,    [ 'user-order' ] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Order', manager_type: orm, group: MENU_GROUP.USER, label: MENU.USER_PROFILE.ORDER, show_in_dashboard: false }

    admin.user.profile.reading:
        class: App\Admin\User\Profile\ReadingUserProfileAdmin
        calls:
            - [ setBaseRouteName,       [ 'admin_user_reading' ] ]
            - [ setBaseRoutePattern,    [ 'user-reading' ] ]
        tags:
            - { name: sonata.admin, model_class: 'App\Entity\Reading', manager_type: orm, group: MENU_GROUP.USER, label: MENU.USER_PROFILE.READING, show_in_dashboard: false }
