security:
    role_hierarchy:
        ROLE_USER:
            - IS_AUTHENTICATED_FULLY
            - IS_AUTHENTICATED_REMEMBERED
            - ROLE_ADMIN_USER_PROFILE_EDIT
            - ROLE_ADMIN_USER_PROFILE_ORDER
            - ROLE_ADMIN_USER_PROFILE_READING
        ROLE_READER:
            - ROLE_USER
        ROLE_EDITOR:
            - ROLE_USER
            - ROLE_ADMIN_USER_LIBRARIAN
            - ROLE_ADMIN_USER_READER
        ROLE_LIBRARIAN:
            - ROLE_EDITOR
        ROLE_ADMIN:
            - ROLE_EDITOR
#            - ROLE_ADMIN_SETTINGS_GENERAL_ALL
#            - ROLE_ADMIN_USER_LIBRARIAN
#            - ROLE_ADMIN_USER_READER
#            - ROLE_ADMIN_USER_PROFILE_EDIT
#            - ROLE_ADMIN_USER_PROFILE_ORDER
#            - ROLE_ADMIN_USER_PROFILE_READING
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_ADMIN_USER_ALL
            - ROLE_ADMIN_USER_ADMIN



#    ROLE_admin_user_all_ALL
#    ROLE_admin_user_admin_ALL
#    ROLE_admin_user_librarian_ALL
#    ROLE_admin_user_reader_ALL
#    ROLE_admin_user_profile_edit_ALL
#    ROLE_admin_user_profile_order_ALL
#    ROLE_admin_user_profile_reading_ALL


    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true

    providers:
        admin_user_provider:
            id: App\Security\AdminUserProvider

        regular_user_provider:
            id: App\Security\RegularUserProvider


    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/library
            lazy: true
            provider: admin_user_provider

            form_login:
                login_path: admin_user_reader_login
                check_path: admin.login_check
                default_target_path: sonata_admin_dashboard

            logout:
                path: admin.logout
                target: admin_user_reader_login

            entry_point: form_login

        main:
            pattern: ^/
            lazy: true
            provider: regular_user_provider

#            json_login:
#                check_path: api.login_check

            form_login:
                login_path: admin_user_reader_login
                check_path: admin.login_check
                default_target_path: sonata_admin_dashboard

            logout:
                path: admin.logout
                target: admin_user_reader_login

            entry_point: form_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # allow unauthenticated users to access the login form
#        - { path: ^/library/login, roles: PUBLIC_ACCESS }
#        - { path: ^/admin/register, roles: PUBLIC_ACCESS }

        # but require authentication for all other admin routes
#        - { path: '^/admin', roles: [PUBLIC_ACCESS] }
#        - { path: '^/admin', roles: [ROLE_EDITOR] }

#        - { path: '^/([a-z]{2}-[a-z]{2})/account/dealer/requests', roles: [ROLE_DEALER_ADMIN, ROLE_DEALER_EMPLOYEE] }
#        - { path: '^/([a-z]{2}-[a-z]{2})/account/dealer', roles: [ROLE_DEALER_ADMIN] }
#
#        - { path: '^/([a-z]{2}-[a-z]{2})/account', roles: [ROLE_USER] }
#
#        - { path: '^/api/users/me/wish-lists', roles: [ROLE_USER] }
#        - { path: '^/api/users/me/profile', roles: [ROLE_USER] }

