sonata_admin:
    title: 'Admin'
    security:
        handler: sonata.admin.security.handler.role
        role_super_admin: ROLE_SUPER_ADMIN

    show_mosaic_button: false
    persist_filters: true
    search: false

    templates:
        layout:  'layout.admin.html.twig'

    breadcrumbs:
        child_admin_route: list

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    default_admin_services:
        label_translator_strategy: sonata.admin.label.strategy.noop

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
