twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        defaultLocale: '%defaultLocale%'
        adminLocale: '%adminLocale%'
        adminTranslationDomain: '%adminTranslationDomain%'

#    form_themes:
#        - '@App/form_themes/default.html.twig'
#        - '@SonataForm/Form/datepicker.html.twig'
#        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

when@test:
    twig:
        strict_variables: true
