###
# !!! IMPORTANT !!!
# Controllers that should be under language prefix must not be configured here
# See configuration for App\Routing\LocaleAwareRouteProvider
###

admin_controllers:
    resource: ../../src/Controller/Admin
    type: annotation
    trailing_slash_on_root: false

#api_controllers:
#    resource: ../../src/Controller/Api
#    type: annotation
#    trailing_slash_on_root: false

#image_controller:
#    resource: ../../src/Controller/MediaController.php
#    type: annotation
#    trailing_slash_on_root: false

#default_controller:
#    resource: ../../src/Controller/DefaultController.php
#    type: annotation
#    trailing_slash_on_root: false

register_controller:
    resource: ../../src/Controller/RegisterController.php
    type: annotation
    trailing_slash_on_root: false

#route_controller:
#    resource: ../../src/Controller/RouteController.php
#    type: annotation
#    trailing_slash_on_root: false
